version: 2.1
jobs:
  update-lambda:
    docker:
      - image: 651179183771.dkr.ecr.us-east-2.amazonaws.com/cicd/aws-base
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Install Lambda Packaging Tool
          command: |
            dotnet tool install --global Amazon.Lambda.Tools --version 3.1.1
            dotnet tool update -g Amazon.Lambda.Tools
      - run:
          name: Create lambda package
          command: ~/.dotnet/tools/dotnet-lambda package -pl ./src/Dotnet.Sample/Dotnet.Sample.csproj
      - run:
          name: Stack up
          command: stackit up --stack-name platformperf --template ./app.yml
workflows:
  version: 2
  deploy:
    jobs:
      - update-lambda:
          context: 10kgDevTest
          filters:
            branches:
              only: master
